### Feed Forward

In [274]:
%run core.ipynb

In [11]:
import numpy as np


def _sigmoid(x):
    return 1 / (1 + np.exp(-x))


def _dx_sigmoid(x):
    return _sigmoid(x) * (1.0 - _sigmoid(x))


def _relu(x):
    return np.maximum(0.0, x)


np.sigmoid =_sigmoid
np.dx_sigmoid =_dx_sigmoid
np.relu =_relu


In [4]:
def feedforward(a, N, x):
    for w, b in N:
        X = a(np.dot(w, x) + b)
    return X


In [40]:
a = lambda x: np.multiply(x, 1)
N = [
    (np.array([[2, 2], 
               [1, -1],
               [2, 2]]), 
     np.array([1, -1, 0])),
    (np.array([[1, 2, 2],
               [0, 0, 3],
               [1, 2, 2]]), 
     np.array([1, -1, -2])),
    (np.array([[2, 2, 1], ]), 
     np.array([1,])),
]
x = np.array([1, -1])

feedforward(a, N, x)
     

array([8])

In [21]:
def get_random_weights_and_biases(k, l, m, layers):
    N = [(np.random.random_sample((l, k)), np.random.random_sample((l)))]
    for i_ in range(layers):
        N.append((np.random.random_sample((l, l)), np.random.random_sample((l))))
    N.append((np.random.random_sample((m, l)), np.random.random_sample((m))))
    return N


In [22]:
a = np.sigmoid
N = get_random_weights_and_biases(2, 3, 2, 3)
X = np.random.random_sample(2)
feedforward(a, N, X)


array([0.90937007, 0.79172075])

In [37]:
class NeuralNetwork:
    
    def __init__(self, a, k, l, m, layers):
        self.a = a
        self.N = get_random_weights_and_biases(k, l, m, layers)

    def __call__(self, X):
        return feedforward(self.a, self.N, X)


In [39]:
nn = NeuralNetwork(np.sigmoid, 2, 3, 2, 3)

x = np.random.random_sample(2)
nn(x)


array([0.7759937 , 0.90856032])