### Feed Forward

In [1]:
%run core.ipynb

In [9]:
def feedforward(a, N, x):
    for w, b in N:
        x = a(np.dot(w, x) + b)
    return x


In [10]:
a = lambda x: np.multiply(x, 1)
N = [
    (np.matrix((2, 2), 
               (1, -1),
               (2, 2)),  
     np.vector(1, -1, 0)),
    (np.matrix((1, 2, 2),
               (0, 0, 3),
               (1, 2, 2)), 
     np.vector(1, -1, -2)),
    (np.matrix((2, 2, 1),), 
     np.vector(1,)),
]
x = np.vector(1, -1)

feedforward(a, N, x)
     

array([8])

In [41]:
def get_random_weights_and_biases(k, l, m=None, layers=0):
    N = [(np.random_matrix(l, k), np.random_vector(l))]
    for _ in range(layers):
        N.append((np.random_matrix(l, l), np.random_vector(l)))
    if m is not None: 
        N.append((np.random_matrix(m, l), np.random_vector(m)))
    return N


In [42]:
a = np.sigmoid
N = get_random_weights_and_biases(2, 3, 2, layers=3)
x = np.random_vector(2)
feedforward(a, N, x)


array([0.89332908, 0.90072456])

In [43]:
class FeedForward:
    
    def __init__(self, a, dim, layers):
        k, l, m = dim
        self.a = a
        self.N = get_random_weights_and_biases(k, l, m, layers)

    def __call__(self, X):
        return feedforward(self.a, self.N, X)


In [48]:
f = FeedForward(np.sigmoid, dim=(2, 3, 2), layers=3)

x = np.random_vector(2)
f(x)


array([0.91897358, 0.77565927])

In [45]:
class FeedForwardSingleLayer(FeedForward):

    def __init__(self, a, da, k, l):
        super().__init__(a, dim=(k, l, None), layers=0)
        self.da = da

    def train(self, T, s=0.01, epochs=50):
        for _ in range(epochs):
            for x, y in T:
                z = self.feedforward(x)
                az, daz = a(z), da(z)
                d = y - az
                w += w + s * d * daz * x
                b = b + s * d * daz
        return w, b
        

In [49]:
f = FeedForwardSingleLayer(np.sigmoid, np.dx_sigmoid, 3, 2)
f.N

[(array([[0.94704461, 0.95936371, 0.94880304],
         [0.17461872, 0.57620442, 0.0036235 ]]),
  array([0.93647866, 0.72904049]))]

In [50]:
from dec2bin import int2dec, int2bin


def get_dec2bin_test_data():
    D = {n: int2dec(n) for n in range(10)}
    B = {n: int2bin(n) for n in range(10)}
    N = []
    for i in range(4):
        N.append([(np.vector(D[n]), np.vector(B[n][i])) for n in range(10)])
    return N


dec2bin = FeedForwardSingleLayer(np.sigmoid, np.dx_sigmoid, 10, 4)
dec2bin.N
get_dec2bin_test_data()


[[(array([[0.99, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]]),
   array([0])),
  (array([[0.01, 0.99, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]]),
   array([1])),
  (array([[0.01, 0.01, 0.99, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]]),
   array([0])),
  (array([[0.01, 0.01, 0.01, 0.99, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]]),
   array([1])),
  (array([[0.01, 0.01, 0.01, 0.01, 0.99, 0.01, 0.01, 0.01, 0.01, 0.01]]),
   array([0])),
  (array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.99, 0.01, 0.01, 0.01, 0.01]]),
   array([1])),
  (array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.99, 0.01, 0.01, 0.01]]),
   array([0])),
  (array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.99, 0.01, 0.01]]),
   array([1])),
  (array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.99, 0.01]]),
   array([0])),
  (array([[0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.99]]),
   array([1]))],
 [(array([[0.99, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]]),
   array([0])),
  (array(